# Generated by Django 3.1.6 on 2021-03-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='question_text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
